# Generated by Django 3.2.7 on 2021-09-23 15:10

from django.db import migrations, models
import picture.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('img', models.ImageField(upload_to=picture.models.img_upload_to)),
            ],
        ),
    ]
