version: 2
updates:
  # Fetch and update latest `pip` packages
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - chandelures
    assignees:
      - chandelures
    commit-message:
      prefix: build
      include: scope
