# Generated by Django 3.2.7 on 2021-09-23 04:53

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_image_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=blog.models.img_upload_to),
        ),
    ]
