# Generated by Django 3.2.7 on 2021-09-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
