"""initial migration

Revision ID: 494c98ece602
Revises: 
Create Date: 2022-01-02 16:13:10.553479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494c98ece602'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('stuff', sa.Boolean(), nullable=True),
    sa.Column('superuser', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['category'], ['categories.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=36), nullable=True),
    sa.Column('value', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user')
    )
    op.create_index(op.f('ix_tokens_value'), 'tokens', ['value'], unique=True)
    op.create_table('about',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['article'], ['articles.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('article', sa.String(length=128), nullable=True),
    sa.Column('user', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('parent', sa.String(length=36), nullable=True),
    sa.Column('reply', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['article'], ['articles.slug'], ),
    sa.ForeignKeyConstraint(['parent'], ['comments.uid'], ),
    sa.ForeignKeyConstraint(['reply'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['user'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('about')
    op.drop_index(op.f('ix_tokens_value'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
