# Generated by Django 3.2.7 on 2021-09-22 15:20

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=userprofile.models.avatar_default, upload_to=userprofile.models.avatar_upload_to),
        ),
    ]
