# Generated by Django 3.2 on 2021-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uid',
            field=models.UUIDField(db_index=True, default=''),
        ),
    ]
