# Generated by Django 3.2.7 on 2021-09-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tag',
            field=models.BooleanField(choices=[(0, 'root'), (1, 'leaf')], default=0, editable=False),
        ),
    ]
