name: build

on:
  push:
  pull_request:

jobs:
  build:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage codecov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Test with pytest and Generate coverage report
        run: |
          coverage run -m pytest
      - name: Upload coverage
        run: |
          codecov
